apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: genai-developer
  namespace: genai
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genai-developer-binding
  namespace: genai
subjects:
- kind: User
  name: developer@example.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: genai-developer
  apiGroup: rbac.authorization.k8s.io
